baseURL = 'https://mtorres95.github.io/weedme-doc/'
languageCode = 'en-us'
title = 'Weed Me Documentation'
theme = 'Relearn'

[params]
  themeVariant = [ "learn" ]
  titleSeparator = "-"

[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]


